-keepattributes Signature
  -keep class sun.misc.Unsafe { *; }
  -keep class com.taobao.** {*;}
  -keep class com.alibaba.** {*;}
  -keep class com.alipay.** {*;}
  -dontwarn com.taobao.**
  -dontwarn com.alibaba.**
  -dontwarn com.alipay.**
  -keep class com.ut.** {*;}
  -dontwarn com.ut.**
  -keep class com.ta.** {*;}
  -dontwarn com.ta.**
  -keep class org.json.** {*;}
  -keep class com.ali.auth.**  {*;}
